version: "3"

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: rom-sql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rom-sql

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: rom-sql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rom_sql
