jobs:
  tests:
    services:
      mysql:
        image: mysql:8.4
        ports:
          - 3307:3306
        env:
          MYSQL_USER: rom-sql
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rom-sql
      postgres:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: rom-sql
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rom-sql
    strategy:
      matrix:
        include:
          - ruby: "3.3"
            coverage: "true"
            fail_on_warnings: "true"
            dry_types_from_master: "true"
            sequel_from_master: "true"
    env:
      APT_DEPS: "libpq-dev libmysqlclient-dev libsqlite3-dev"
      FAIL_ON_WARNINGS: ${{matrix.fail_on_warnings}}
      DRY_TYPES_FROM_MASTER: ${{matrix.dry_types_from_master}}
      SEQUEL_FROM_MASTER: ${{matrix.sequel_from_master}}
